/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

export interface Config {
  collections: {
    users: User;
    products: Product;
    media: Media;
    orders: Order;
    product_offer: ProductOffer;
    product_varient: ProductVarient;
    product_review: ProductReview;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  globals: {};
}
export interface User {
  id: string;
  products?: (string | Product)[] | null;
  product_offer?: (string | ProductOffer)[] | null;
  phone: number;
  role: 'admin' | 'user';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  _verified?: boolean | null;
  _verificationToken?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  password: string | null;
}
export interface Product {
  id: string;
  user?: (string | null) | User;
  name: string;
  description?: string | null;
  price: number;
  avg_rating?: number | null;
  have_varient: 'yes' | 'no';
  category: 'sofa_and_seating' | 'mattresses' | 'home_decor' | 'furnishings';
  subcategory: (
    | 'sofa'
    | 'l_shape_sofa'
    | '3_seat_sofa'
    | '2_seat_sofa'
    | '1_seat_sofa'
    | 'recliners'
    | '3_seat_recliner'
    | '2_seat_recliner'
    | '1_seat_recliner'
    | 'sofa_cum_bed'
    | 'bean_bag'
    | 'spring_mattresses'
    | 'pocket_spring_mattress'
    | 'bonnell_spring_mattress'
    | 'memory_foam_mattress'
    | 'latex_foam_mattress'
    | 'bonded_foam_mattress'
    | 'coir_mattress'
    | 'vases'
    | 'table_vases'
    | 'floor_vases'
    | 'table_decor'
    | 'decorative_boxes'
    | 'desk_organizers'
    | 'magazine_racks'
    | 'photo_frames'
    | 'single'
    | 'collage'
    | 'clip_photo'
    | 'candles'
    | 'decorative_candles'
    | 'scented_candles'
    | 'tea_lights_candles'
    | 'outdoor_decor'
    | 'artificial_grass'
    | 'artificial_plants'
    | 'artificial_flowers'
    | 'vertical_garden'
    | 'wall_decor'
    | 'wall_art'
    | 'wall_hangings'
    | 'wallpaper_for_wall'
    | 'wall_stickers'
    | 'wall_decor'
    | 'wall_art'
    | 'wall_hangings'
    | 'wallpaper_for_wall'
    | 'wall_stickers'
    | 'bed_sheets'
    | 'king_bed_sheets'
    | 'queen_bed_sheets'
    | 'single_bed_sheets'
    | 'blankets_and_quilts'
    | 'quilts'
    | 'dohars'
    | 'blankets'
    | 'curtains'
    | 'door_curtains'
    | 'window_curtains'
    | 'blinds'
    | 'carpets'
    | '3_by_5'
    | '5_by_7'
    | '6_by_9'
    | '8_by_10'
    | '9_by_12'
    | 'cushions_and_covers'
    | 'pillow'
    | 'pillow_covers'
    | 'cushions'
    | 'cushion_cover'
    | 'bolster'
    | 'furnishings'
    | 'towels'
    | 'comforters'
    | 'door_mats'
  )[];
  size: string;
  unit: 'ft' | 'inch';
  approvedForSale?: ('pending' | 'approved' | 'denied') | null;
  product_offer?: (string | ProductOffer)[] | null;
  images: {
    image: string | Media;
    id?: string | null;
  }[];
  updatedAt: string;
  createdAt: string;
}
export interface ProductOffer {
  id: string;
  user?: (string | null) | User;
  coupon_code: string;
  min_order_value: number;
  start_date: string;
  end_date: string;
  updatedAt: string;
  createdAt: string;
}
export interface Media {
  id: string;
  user?: (string | null) | User;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    tablet?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
export interface Order {
  id: string;
  _isPaid: boolean;
  user: string | User;
  products: (string | Product)[];
  updatedAt: string;
  createdAt: string;
}
export interface ProductVarient {
  id: string;
  products: (string | Product)[];
  color?: ('red' | 'green' | 'blue') | null;
  size: string;
  unit: 'ft' | 'in';
  updatedAt: string;
  createdAt: string;
}
export interface ProductReview {
  id: string;
  user?: (string | null) | User;
  products?: (string | null) | Product;
  rating: number;
  rewiew?: string | null;
  updatedAt: string;
  createdAt: string;
}
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}